// Path: server/src/domain/fullReportPdf/reportFieldLabels.ts

export const REPORT_FIELD_LABELS: Record<string, Record<string, string>> = {
  incoming_alert: {
    spindleIssue: "Spindle Issue",
    firstTimeCustomer: "First Time Customer",
    customerPaymentPending: "Payment Pending",
    dispatchWithoutClearance: "Dispatch w/o Clearance",
    dispatchWithoutClearanceReason: "Clearance Reason",
    salesApproval: "Sales Approval",
    financeApproval: "Finance Approval",
  },
  checksheet: {
    box: "Box",
    toolHolder: "Tool holder",
    cylinder: "Cylinder",
    proxySwitch: "Proxy Switch",
    tenon: "Tenon",
    pulley: "Pulley",
    drawbar: "Drawbar",
    speedSensor: "Speed sensor",
    spindleCondition: "Spindle Condition",
  },
  damage_report: {
    bearingDamage: "Bearing",
    shadowTaper: "Shaft Taper",
    shaftOdDamage: "Shaft OD",
    mechanicalSeal: "Mechanical Seal",
    pulleyDamage: "Pulley",
    encoderDamage: "Encoder",
    rotaryUnion: "Rotary Union",
    spacerDistanceSleeve: "Spacer/Distance Sleeve",
    tenonDamage: "Tenon",
    oRings: "O-rings",
    drawbarColletes: "Drawbar / colletes",
    springDamage: "Drawbar Disc/Helical Spring",
    sensorsDamage: "Sensors",
  },
  drawbar_details: {
    arrangement: "Drawbar Details and arrangement",
    drawBarArrangementOd: "OD",
    drawBarArrangementId: "ID",
    drawBarArrangementThickness: "Thickness",
    drawBarArrangementHeight: "Height",
    drawBarArrangementQuantity: "Total quantity",
    drawBarArrangementLength: "Total length",
    beforeDismantlingClampingForce: "Before dismantling clamping force (kg-f)",
  },
  final_inspection: {
    afterGrindingROofShaft: "After grinding R/O of shaft (mm)",
    goNoGo: "GO-NOGO",
    blueMatching: "Blue matching",
    spacerSizeOfNNBearing: "Spacer size of NN Bearing (mm)",
    housingDepth: "Housing depth (mm)",
    bearingStackLength: "Bearing stack length (mm)",
    preloadOfCover: "Preload of cover (mm)",
    boreRO: "Bore R/O (mm)",
    frontBearingTool: "Front Bearing Tol (mm)",
    rearSideRO: "Rear side R/O (mm)",
    faceROHSK: "Face R/O (mm)",
    mandrelRO300WithStud: "Mandrel R/O at 300mm with Stud (mm)",
    mandrelRO300WithDrawbar: "Mandrel R/O at 300mm (Drawbar) (mm)",
    clampingForceFinal: "Clamping force (kg-f / Nm)",
    axialPlay: "Axial Play (mm)",
    radialPlay: "Radial Play (mm)",
    axialFloat: "Axial float (mm)",
    rearBearingTolerance: "Rear Bearing tol (mm)",
    totalShaftHeightAfterRework: "Total shaft height after rework (mm)",
    taperOdRunout: "Taper OD runout",
  },
  testing_balancing: {
    stabilizedTemperature: "Stabilized Temperature at max temperature",
    residualImbalanceFront: "Spindle Vibration — Front Side",
    residualImbalanceRear: "Spindle Vibration — Rear Side",
    remark: "Remark",
  },
  order_closure: {
    closureDate: "Closure Date",
    warrantyValidTill: "Warranty Valid Till",
    packId: "Pack Id",
    invoiceNo: "Invoice Number",
    invoiceDate: "Invoice Date",
    outstandingBalanceClosure: "Outstanding Balance",
    financeApprovalClosure: "Finance Approval (Closure)",
  },
  remarks_for_customer: {
    remark: "Remarks",
  },
};

export const REPORT_DISPLAY_TITLES: Record<string, string> = {
  incoming_alert: "Incoming Alert",
  checksheet: "Checksheet",
  damage_report: "Damage Report",
  old_bearing_report: "Old Bearing Report",
  new_bearing_report: "New Bearing Report",
  electrical_test: "Electrical Test",
  drawbar_details: "Drawbar Details",
  in_process_inspection: "In Process Inspection",
  final_inspection: "Final Inspection",
  testing_balancing: "Testing and Balancing",
  remarks_for_customer: "Remarks for Customer",
  deviations: "Deviations",
  order_closure: "Order Closure",
};
